variable "volume_type" {}
variable "instance_count" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "key_name" {}
variable "volume_size" {}
variable "rg" {}
variable "vnet" {}
variable "siro" {}
variable "sirp" {}
variable "sirs" {}
variable "sirv" {}
variable "admin_username" {}
variable "admin_ssh_key" {}
