---
- name: Restore DB
  hosts: postgres
  become: true
  tasks:
    - name: Stop db
      command: su - postgres -c 'pg_ctl -D $PGDATA stop -m smart'
      register: restore_stop_db_status
      ignore_errors: true

    - name: Display status
      debug:
        var: restore_stop_db_status

    - name: Wait for PostgreSQL to stop
      wait_for:
        path: "/var/lib/postgresql/14/main/postmaster.pid"
        state: absent
      when: restore_stop_db_status.rc == 0

    - name: Delete, copy, move, and link files
      shell: |
        PGDATA=/var/lib/postgresql/14/main
        export PGDATA
        rm -rf $PGDATA/*
        rm -rf /var/lib/postgresql/14/log/*
        cp -R /var/lib/postgresql/14/backups/main/* $PGDATA/
        mv $PGDATA/pg_wal /var/lib/postgresql/14/log
        ln -s /var/lib/postgresql/14/log/pg_wal $PGDATA/pg_wal

    - name: Give permissions
      file:
        path: /var/lib/postgresql/14/main/
        owner: postgres
        group: postgres
        recurse: yes

    - name: Set directory permissions
      file:
        path: /var/lib/postgresql/14/main/
        mode: "0700"
        recurse: yes
        state: directory

    - name: Reboot machine
      reboot:
        reboot_timeout: 600

    - name: Stop PostgreSQL if already running
      become: true
      shell: sudo kill $(cat /var/lib/postgresql/14/main/postmaster.pid)
      ignore_errors: true

    - name: Start DB
      become: true
      command: su - postgres -c 'pg_ctl -D $PGDATA start'
      register: restore_start_db_status

    - name: Display status
      debug:
        var: restore_start_db_status
