source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "nextgen-devops-team"
  }
  image_offer                       = "0001-com-ubuntu-server-jammy"
  image_publisher                   = "canonical"
  image_sku                         = "22_04-lts"
  location                          = "East US"
  managed_image_name                = "myPackerImage"
  managed_image_resource_group_name = "Intel-RFI-RG"
  os_type                           = "Linux"
  vm_size                           = "Standard_B1ms"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

	provisioner "ansible" {
      		playbook_file = "./db.yml"
    	}
}
